title ダーツワークフロー

@startuml

!theme vibrant

|脳|
|顔|
|足|
|左手|
|右腕|
start
|左手|
:ダーツを3本持つ;
|脳|
:ターゲットを決定;
|足|
:クローズドスタンス;
:左足を床につける;
|右手|
:ダーツ1本握る;
|右腕|
:ボードに腕を伸ばす;

#pink:腕を一番右側
まで伸ばす;
:指の通る道を意識;
|顔|
:ボードに
顔を向ける;
|右腕|
:セットアップ;
':60°ぐらいに構える;
note
肘の場所で
成功率変化
end note
|脳|

#palegreen:ラインを考える;

:セットアップ位置までの
指の流れを確認;

|右腕|
:カウント開始;

note
    忘れない
end note


#Aqua:(１)


:テイクバックで
目の下に引く;

#pink:西哲平流テイクバック;

#Aqua:(２)


#pink:肘固定意識;

note
    固定が甘い
    →飛ばない
end note

#pink:肘の裏側意識;

note
    指の道が
    肘の左側
end note

|右腕|
#pink:ゆっくり
腕始動;
|指|
:最速でリリース;
note
    大事な局面
        =バグる 
end note


#Aqua:(３)


:フォロースルー;
#pink:東田臣流
円月殺法投;
end 

note
　これからの課題
    ・優しくスロー
　・左に降らない投げ方
end note
@enduml
