@startuml
title ダーツワークフロー



!theme vibrant

|脳|
|顔|
|足|
|上半身|
|左手|
|右腕|
|左手|

start

/'################'/
/'セットアップ前'/
/'################'/
:ダーツを3本持つ;
|脳|
:ターゲットを決定;
#gray:ターゲットに
顔を向ける;

|足|
:右足をスローラインに合わせる
（オープンスタンスとクローズスタンスの間）;
#palegreen:左足を床につける;
note
  軸が体中央に集まる
end note
/'
################
##pink:左足を右足よりも
#後ろに下げる;
################
'/

|左手|
:ダーツを
右手に近づける;
|右手|
:ダーツ1本握る;
#palegreen:親指と人差し指
第二関節で挟む;
note
  4スタンス講座で指摘された
  人差し指の左端で挟む
end note

|右腕|
:ボードに腕を伸ばす;
/'
#pink:腕の右側のラインに体幹を合わせる;
'/

|顔|
#pink:右目でターゲットを
ロック;
|右腕|
/'
:ゼロポジションで
ボードにスムーズに伸ばせる方向を探す;
'/

/'################'/
/'セットアップ'/
/'################'/

:セットアップ;
|脳|
#pink:親指と人差し指の間、
右腕の左端と空間の線、
右目
筋を通す意識;
note
  直線ではない
  円弧のイメージ
end note
note
ターゲットが右腕に隠れて、
半分見れる形となる。
end note

|顔|

|上半身|
#pink:テイクバック時に
体が前に行かないようにする;

|右腕|
:セットアップ位置に
腕を持ってくる;

|右腕|
:カウント開始で前に押す;

note
    ユーミングしない
    カウント忘れない
end note

note
  セットアップする理由
  テイクバックする際に手を振る高さ、角度、方向を確認できる
end note

#Aqua:(１)

|右手|

#palegreen:テイクバックで
右顎(の下)に引く;

note
    狙いはここまで
end note


:肩の付け根、右顎に引く;

note
    右顎にテイクバックすると
    気持ちが良い。
end note

#Aqua:(２)
:カウントタイミングは
テークバック完了;
/'
#pink:肘固定意識;
note
    固定が甘い
    →飛ばない
end note
#pink:肘の裏側が意識;
note
    指の道が
    肘の左側
end note
'/

|右腕|
#pink:ゆっくり
腕始動;
:鞭のようにしなる
　　イメージ;
note
  リリース速度のみイメージ
end note

|指|
#palegreen:超重要。
最速でリリース;

#Aqua:(３)

/'
:スローしながら、
人差し指をターゲットに
伸ばす;
:第二関節で押し込む;
note
  4スタンス講座で指摘された
  第二関節で押し込む
end note
'/

:親指、人差し指をしならせる。
フォークのイメージ;
:フォロースルーで手を下に向ける;
note
  リリースが早いと
  フォロースルーが綺麗になる
end note

end
@enduml
