@startuml
title ダーツワークフロー



!theme vibrant

|脳|
|顔|
|足|
|上半身|
|左手|
|右腕|
|左手|
start
:ダーツを3本持つ;
|脳|
:ターゲットを決定;
|足|
:右足をスローラインに合わせる
（クローズドスタンス）;
#palegreen:左足を床につける;
note
  軸が体中央に集まる
end note
/'
################
##pink:左足を右足よりも
#後ろに下げる;
################
'/

|左手|
:右手に近づける;
|右手|
:ダーツ1本握る;
#palegreen:親指と人差し指
第二関節で挟む;
note
  4スタンス講座で指摘された
  人差し指の左端で挟む
end note

|右腕|
:ボードに腕を伸ばす;

|顔|
:ボードに
顔を向ける;
|右腕|
:ゼロポジションで
ボードにスムーズに伸ばせる方向を探す;
:セットアップ;
|脳|
#pink:グリップ部分、
右腕の左端、
右肘、
右鎖骨、
右目
の中央の筋を通す意識;
|顔|
#pink:右目で狙う;

|上半身|
#pink:体が前に行かないようにする;

|右腕|
:指の通る道を意識。
右腕の左端の線で狙う。;
note
ターゲットが右腕に隠れて、
半分見れる形となる。
end note

|右腕|
:カウント開始;

note
    忘れない
end note


#Aqua:(１)

|右手|

#palegreen:テイクバックで
右目(の下)、右肩の鎖骨に引く;

:テイクバックできるところまで
今一度引く;

note
    肩にテイクバックすると
    気持ちが良い。
end note

#Aqua:(２)

/'
#pink:肘固定意識;
note
    固定が甘い
    →飛ばない
end note
#pink:肘の裏側が意識;
note
    指の道が
    肘の左側
end note
'/

|右腕|
#pink:ゆっくり
腕始動;
:鞭のようにしなる
　　イメージ;
note
  リリース速度が一番大事
  投げた後は手が下を向くこと
end note
|指|
#palegreen:超重要。
最速でリリース;

#Aqua:(３)

:第二関節で押し込む;
note
  4スタンス講座で指摘された
  第二関節で押し込む
end note

:フォロースルー;
note
  リリースが早いと
  フォロースルーが綺麗になる
end note

end
@enduml
